In [4]:
import numpy as np

a = np.arange(12)
print (a)
x = np.random.randn(2,3)
print (x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[-1.79576809 -0.42535863 -0.01538742]
 [-1.47819749 -0.69465131 -0.76994097]]


In [5]:
# 矩阵相乘
print (np.dot(x, x.T))

[[3.40594976 2.96182321]
 [2.96182321 3.26041738]]


In [6]:
# 对应元素相乘
print (np.multiply(a,a))

[  0   1   4   9  16  25  36  49  64  81 100 121]


In [40]:
# reshape，用于图片转向量，或者把(5,)转(5,1)
# （1,2） 表示 [[0,1]]
# （3,1,2） 表示三个（1，2）, [[[0,1]],
#                           [[2,3]],
#                           [[4,5]]],
# (2,3,1,2) 表示两个(3,1,2)
a = np.arange(12)
print (a.reshape(2,3,1,2))

# 把维度(a,b,c,d)的矩阵铺成(b*c*d,a)的矩阵
b = a.reshape((3,4))
print (b)
# 不知道行数，列数为1
print (b.reshape(-1,1))
# 不知道列数，行数为2
print (b.reshape(2,-1))

[[[[ 0  1]]

  [[ 2  3]]

  [[ 4  5]]]


 [[[ 6  7]]

  [[ 8  9]]

  [[10 11]]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [10]:
# tile 沿x，y轴复制
b = np.array([[1,2],[3,4]])
#沿x轴复制2倍
print (np.tile(b, 2))
#沿y轴复制两倍
print (np.tile(b, (2,1)))


[[1 2 1 2]
 [3 4 3 4]]
[[1 2]
 [3 4]
 [1 2]
 [3 4]]


In [12]:
# 求和,均值mean同解
c = np.array([[0,2,1],[3,5,6],[0,1,1]])
# 全部求和
print (c.sum())
# 每一列运算
print (c.sum(axis=0))
# 每一行运算
print (c.sum(axis=1))

19
[3 8 8]
[ 3 14  2]


In [16]:
# 索引值升序
x = np.array([3,1,2])
print (x.argsort())
# 降序
print (np.argsort(-x))
# 值排序
print (x[np.argsort(x)])

[1 2 0]
[0 2 1]
[1 2 3]


In [18]:
# 初始化array
print (np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
# 极值
c = np.array([[0,2,1],[3,5,6],[0,1,1]])
# 每一列最小值
print (c.min(0))
# 每一行最小值
print (c.min(1))

[0 1 1]
[0 3 0]


In [22]:
# 取值
c = np.array([[0,2,1],[3,5,6],[0,1,1]])
print (c[0][1])
print (c[0,1])

2
2


In [23]:
# 生成数组
print (np.arange(3,9,2))

[3 5 7]


In [33]:
# 非零元素索引值
a = np.array([[0,0,3],[0,0,0],[0,0,9]])
print (a)
# array([0,2]): 第0，2行有非零元素
# array([2,2]): 第2，2列有非零元素
print (np.nonzero(a))

# (...,) 逗号后面没有的原因是b是一个秩为1的数组, 少一个[]
b = np.array([1,2,3,0,4,5,0])
print (np.nonzero(b))

c = np.mat(np.eye(4))
print (c)
print (np.nonzero(c[:,1]<0.5))

[[0 0 3]
 [0 0 0]
 [0 0 9]]
(array([0, 2]), array([2, 2]))
(array([0, 1, 2, 4, 5]),)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(array([0, 2, 3]), array([0, 0, 0]))


In [35]:
# 数组转列表
a = np.array([[0,0,3],[0,0,0],[0,0,9]])
print (a)
print (a.tolist())

[[0 0 3]
 [0 0 0]
 [0 0 9]]
[[0, 0, 3], [0, 0, 0], [0, 0, 9]]
